### PR TITLE
Upgrade to cmark 0.6

### PR DESCRIPTION
**Pull request by puffnfresh**
Without this, I get ambiguous linking problems because glibc includes
unistd.h which has a 'link' type defined.

### CODE REVIEW

**Comment by puffnfresh** [comment]
Whoops, this needs a submodule update for the CommonMark repo.

**Comment by soimort** [comment]
It seems the new reference implementation has been moved to https://github.com/jgm/cmark . I'll take a look at that when I have some time...

**Comment by puffnfresh** [comment]
@soimort I've now upgraded to the first version of cmark. It now seems to work well for me!

We should upgrade to a later version when we have time.

**Comment by soimort** [comment]
Big thanks!

**Pull request merged**
